# Generated by Django 4.2.16 on 2025-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
