# Generated by Django 4.2.16 on 2025-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stkpushtransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushtransaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
