# Generated by Django 4.2.16 on 2025-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stkpushtransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushtransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
